"""HTML to PDF report generator using WeasyPrint."""

import os
import markdown
from jinja2 import Template

REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
@page {
    size: A4;
    margin: 2cm 2.5cm;
    @bottom-center {
        content: "MindIQ Personality Report — Page " counter(page) " of " counter(pages);
        font-size: 9px;
        color: #94a3b8;
    }
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1e293b;
}
.cover {
    page-break-after: always;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    min-height: 90vh;
    text-align: center;
}
.cover h1 {
    font-size: 32pt;
    background: linear-gradient(135deg, #6366f1, #8b5cf6);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-bottom: 16px;
}
.cover .subtitle {
    font-size: 14pt;
    color: #64748b;
    margin-bottom: 40px;
}
.cover .date {
    font-size: 10pt;
    color: #94a3b8;
}
.scores-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin: 24px 0;
    page-break-inside: avoid;
}
.score-card {
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 16px;
}
.score-card .dim-name {
    font-weight: 700;
    font-size: 11pt;
    color: #4f46e5;
    margin-bottom: 4px;
}
.score-bar-bg {
    background: #f1f5f9;
    border-radius: 4px;
    height: 8px;
    margin-top: 8px;
}
.score-bar {
    height: 8px;
    border-radius: 4px;
    background: linear-gradient(90deg, #6366f1, #8b5cf6);
}
h2 { font-size: 16pt; color: #4f46e5; margin-top: 28px; margin-bottom: 12px; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }
h3 { font-size: 13pt; color: #1e293b; margin-top: 20px; margin-bottom: 8px; }
h4 { font-size: 11pt; color: #6366f1; margin-top: 16px; margin-bottom: 6px; }
p { margin-bottom: 10px; }
ul, ol { margin-left: 20px; margin-bottom: 10px; }
li { margin-bottom: 4px; }
strong { color: #1e293b; }
.footer-note {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #e2e8f0;
    font-size: 9pt;
    color: #94a3b8;
    text-align: center;
}
</style>
</head>
<body>
<div class="cover">
    <h1>MindIQ</h1>
    <div class="subtitle">Your Comprehensive Personality Report</div>
    <div class="subtitle" style="font-size:12pt;">Big Five Personality Assessment</div>
    <div class="date">Generated on {{ date }}</div>
</div>

<h2>Score Overview</h2>
<div class="scores-grid">
{% for dim, score in scores.items() %}
<div class="score-card">
    <div class="dim-name">{{ dim | title }}</div>
    <div>Score: {{ score }}/100 &nbsp;|&nbsp; {{ percentiles[dim] }}th percentile</div>
    <div class="score-bar-bg"><div class="score-bar" style="width: {{ score }}%"></div></div>
</div>
{% endfor %}
</div>

<div class="report-body">
{{ report_html }}
</div>

<div class="footer-note">
    This report was generated by MindIQ using the IPIP-NEO Big Five personality framework.<br>
    For informational purposes only. Not a clinical assessment.<br>
    &copy; 2026 MindIQ. All rights reserved.
</div>
</body>
</html>"""


def render_report_html(report_md: str, scores: dict, percentiles: dict) -> str:
    """Convert markdown report to styled HTML."""
    from datetime import datetime

    report_body_html = markdown.markdown(report_md, extensions=["extra"])
    template = Template(REPORT_HTML_TEMPLATE)
    return template.render(
        report_html=report_body_html,
        scores=scores,
        percentiles=percentiles,
        date=datetime.now().strftime("%B %d, %Y"),
    )


def _ensure_macos_homebrew_libpath() -> None:
    """Best-effort fix for WeasyPrint dynamic libraries on macOS/Homebrew."""
    lib_path = "/opt/homebrew/lib"
    if not os.path.isdir(lib_path):
        return

    current = os.environ.get("DYLD_LIBRARY_PATH", "")
    if lib_path not in current.split(":"):
        os.environ["DYLD_LIBRARY_PATH"] = f"{lib_path}:{current}" if current else lib_path


def generate_pdf_bytes(html_content: str) -> tuple[bytes, str | None]:
    """Generate PDF from HTML using WeasyPrint.

    Returns:
        (pdf_bytes, error_message)
    """
    import logging

    try:
        _ensure_macos_homebrew_libpath()
        from weasyprint import HTML

        data = HTML(string=html_content).write_pdf()
        if not data:
            return b"", "WeasyPrint returned empty bytes"
        return data, None
    except Exception as e:
        logging.exception("PDF generation failed")
        msg = str(e).strip()
        if not msg:
            msg = f"{type(e).__name__}"
        else:
            msg = f"{type(e).__name__}: {msg}"
        return b"", msg
