"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { fetchStats } from "@/lib/api";

export default function LandingPage() {
  const [stats, setStats] = useState({ total_assessments: 1247, today_assessments: 47 });

  useEffect(() => {
    fetchStats().then(setStats).catch(() => {});
  }, []);

  return (
    <main className="flex flex-col min-h-screen">
      {/* Hero */}
      <section className="gradient-bg text-white px-6 py-20 md:py-32 text-center relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-10 left-10 w-72 h-72 bg-white rounded-full blur-3xl" />
          <div className="absolute bottom-10 right-10 w-96 h-96 bg-purple-300 rounded-full blur-3xl" />
        </div>
        <div className="relative z-10 max-w-3xl mx-auto">
          <div className="text-sm font-medium tracking-widest uppercase text-indigo-200 mb-4">
            Scientific Personality Assessment
          </div>
          <h1 className="text-4xl md:text-6xl font-bold leading-tight mb-6">
            Discover Your True
            <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-200 to-white">
              Personality Profile
            </span>
          </h1>
          <p className="text-lg md:text-xl text-indigo-100 mb-8 max-w-2xl mx-auto">
            AI-powered personality assessment based on the Big Five model — the
            gold standard in psychology. Get personalized career insights
            tailored for you.
          </p>
          <Link
            href="/start"
            className="inline-block bg-white text-indigo-600 font-bold text-lg px-10 py-4 rounded-full hover:bg-indigo-50 transition-all shadow-lg hover:shadow-xl pulse-glow"
          >
            Start Free Assessment
          </Link>
          <p className="mt-6 text-indigo-200 text-sm">
            {stats.today_assessments.toLocaleString()}+ assessments completed
            today
          </p>
        </div>
      </section>

      {/* Features */}
      <section className="py-16 px-6 bg-white">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12 text-slate-800">
            Why MindIQ?
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: "&#9670;",
                title: "Scientific Foundation",
                desc: "Built on IPIP-NEO Big Five — validated across 50+ countries with millions of participants. The most reliable personality framework in psychology.",
              },
              {
                icon: "&#9733;",
                title: "AI-Powered Insights",
                desc: "Your report is uniquely generated by advanced AI, providing personalized analysis that goes far beyond generic personality descriptions.",
              },
              {
                icon: "&#9654;",
                title: "Career Guidance",
                desc: "Get specific career recommendations aligned with your personality traits, tailored to opportunities in the Indian professional landscape.",
              },
            ].map((f) => (
              <div
                key={f.title}
                className="bg-slate-50 rounded-2xl p-8 border border-slate-100 hover:shadow-lg transition-shadow"
              >
                <div
                  className="text-3xl text-indigo-500 mb-4"
                  dangerouslySetInnerHTML={{ __html: f.icon }}
                />
                <h3 className="text-xl font-semibold mb-3 text-slate-800">
                  {f.title}
                </h3>
                <p className="text-slate-600 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-16 px-6 bg-slate-50">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-12 text-slate-800">
            How It Works
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                step: "01",
                title: "Take the Assessment",
                desc: "Answer 40 quick questions about your personality preferences. No right or wrong answers.",
              },
              {
                step: "02",
                title: "AI Analyzes Your Profile",
                desc: "Our AI engine processes your responses using the Big Five personality framework.",
              },
              {
                step: "03",
                title: "Unlock Your Report",
                desc: "Get a comprehensive personality report with career matches and growth strategies.",
              },
            ].map((s) => (
              <div key={s.step} className="text-center">
                <div className="w-16 h-16 rounded-full gradient-bg text-white text-2xl font-bold flex items-center justify-center mx-auto mb-4">
                  {s.step}
                </div>
                <h3 className="text-lg font-semibold mb-2 text-slate-800">
                  {s.title}
                </h3>
                <p className="text-slate-600">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Social proof */}
      <section className="py-12 px-6 bg-white text-center">
        <div className="max-w-2xl mx-auto">
          <p className="text-4xl font-bold gradient-text mb-2">
            {stats.total_assessments.toLocaleString()}+
          </p>
          <p className="text-slate-600">
            Personality assessments completed worldwide
          </p>
        </div>
      </section>

      {/* CTA */}
      <section className="gradient-bg text-white py-16 px-6 text-center">
        <h2 className="text-3xl font-bold mb-4">
          Ready to Discover Yourself?
        </h2>
        <p className="text-indigo-100 mb-8 max-w-lg mx-auto">
          Take 5 minutes to understand your personality — it could change the
          direction of your career.
        </p>
        <Link
          href="/start"
          className="inline-block bg-white text-indigo-600 font-bold text-lg px-10 py-4 rounded-full hover:bg-indigo-50 transition-all shadow-lg"
        >
          Start Free Assessment
        </Link>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-8 px-6 text-center text-sm">
        <div className="flex justify-center gap-6 mb-3">
          <Link href="/dashboard" className="hover:text-white transition-colors">
            My Assessments
          </Link>
          <Link href="/start" className="hover:text-white transition-colors">
            New Assessment
          </Link>
        </div>
        <p>&copy; 2026 MindIQ. All rights reserved.</p>
        <p className="mt-1">
          Based on the IPIP-NEO Big Five personality framework.
        </p>
      </footer>
    </main>
  );
}
