"""IPIP-NEO question bank with 100 India-adapted items and metadata for personalization."""

from __future__ import annotations

from config import settings

DIMENSIONS = ["openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism"]

# 100 items, 20 per dimension.
QUESTIONS: list[dict] = [
    # OPENNESS (1-20)
    {"id": "O1", "text": "I enjoy exploring career paths that are very different from my current one.", "dimension": "openness", "reverse": False, "facet": "curiosity", "scenes": ["student", "fresher", "career_switch"], "role": "core", "difficulty": "easy", "tags": ["career"], "language": "en"},
    {"id": "O2", "text": "I like learning skills outside my formal education.", "dimension": "openness", "reverse": False, "facet": "learning", "scenes": ["student", "fresher", "it"], "role": "core", "difficulty": "easy", "tags": ["learning"], "language": "en"},
    {"id": "O3", "text": "I often connect ideas from different fields to solve work problems.", "dimension": "openness", "reverse": False, "facet": "integration", "scenes": ["it", "startup", "consulting"], "role": "core", "difficulty": "medium", "tags": ["problem-solving"], "language": "en"},
    {"id": "O4", "text": "I am curious about how new technology may change my profession.", "dimension": "openness", "reverse": False, "facet": "innovation", "scenes": ["it", "ops", "startup"], "role": "core", "difficulty": "easy", "tags": ["technology"], "language": "en"},
    {"id": "O5", "text": "I prefer jobs where I can experiment with new methods.", "dimension": "openness", "reverse": False, "facet": "experimentation", "scenes": ["startup", "consulting", "design"], "role": "core", "difficulty": "medium", "tags": ["work-style"], "language": "en"},
    {"id": "O6", "text": "I actively seek perspectives from people unlike me.", "dimension": "openness", "reverse": False, "facet": "diversity", "scenes": ["team", "enterprise", "global"], "role": "core", "difficulty": "easy", "tags": ["collaboration"], "language": "en"},
    {"id": "O7", "text": "I feel energized when I work on unfamiliar tasks.", "dimension": "openness", "reverse": False, "facet": "novelty", "scenes": ["startup", "fresher", "ops"], "role": "scene", "difficulty": "medium", "tags": ["adaptability"], "language": "en"},
    {"id": "O8", "text": "I enjoy reading or watching content about future trends in India.", "dimension": "openness", "reverse": False, "facet": "future_orientation", "scenes": ["student", "founder", "it"], "role": "scene", "difficulty": "easy", "tags": ["india-market"], "language": "en"},
    {"id": "O9", "text": "I can imagine multiple career versions of myself.", "dimension": "openness", "reverse": False, "facet": "identity_flexibility", "scenes": ["career_switch", "fresher", "student"], "role": "scene", "difficulty": "medium", "tags": ["career"], "language": "en"},
    {"id": "O10", "text": "I value creativity as much as stability in work.", "dimension": "openness", "reverse": False, "facet": "creativity_balance", "scenes": ["startup", "enterprise", "it"], "role": "scene", "difficulty": "easy", "tags": ["values"], "language": "en"},
    {"id": "O11", "text": "I avoid roles that require me to rethink my usual approach.", "dimension": "openness", "reverse": True, "facet": "rigidity", "scenes": ["career_switch", "ops", "enterprise"], "role": "reverse", "difficulty": "easy", "tags": ["work-style"], "language": "en"},
    {"id": "O12", "text": "I rarely question the normal way of doing things.", "dimension": "openness", "reverse": True, "facet": "conformity", "scenes": ["enterprise", "gov", "ops"], "role": "reverse", "difficulty": "easy", "tags": ["mindset"], "language": "en"},
    {"id": "O13", "text": "I feel uncomfortable when a project has no fixed template.", "dimension": "openness", "reverse": True, "facet": "ambiguity", "scenes": ["startup", "consulting", "it"], "role": "reverse", "difficulty": "medium", "tags": ["uncertainty"], "language": "en"},
    {"id": "O14", "text": "I prefer repeating proven routines over trying new ideas.", "dimension": "openness", "reverse": True, "facet": "routine", "scenes": ["ops", "enterprise", "student"], "role": "reverse", "difficulty": "easy", "tags": ["habits"], "language": "en"},
    {"id": "O15", "text": "I lose interest when discussions become abstract or strategic.", "dimension": "openness", "reverse": True, "facet": "abstraction", "scenes": ["management", "founder", "consulting"], "role": "reverse", "difficulty": "medium", "tags": ["thinking"], "language": "en"},
    {"id": "O16", "text": "I avoid cross-functional collaboration unless required.", "dimension": "openness", "reverse": True, "facet": "cross_function", "scenes": ["enterprise", "it", "ops"], "role": "reverse", "difficulty": "easy", "tags": ["collaboration"], "language": "en"},
    {"id": "O17", "text": "I believe career decisions should only follow tradition.", "dimension": "openness", "reverse": True, "facet": "tradition", "scenes": ["family_pressure", "student", "career_switch"], "role": "scene", "difficulty": "easy", "tags": ["family"], "language": "en"},
    {"id": "O18", "text": "I find innovation overrated for most jobs.", "dimension": "openness", "reverse": True, "facet": "innovation_attitude", "scenes": ["it", "enterprise", "ops"], "role": "scene", "difficulty": "easy", "tags": ["innovation"], "language": "en"},
    {"id": "O19", "text": "I would rather copy existing solutions than design my own.", "dimension": "openness", "reverse": True, "facet": "originality", "scenes": ["student", "fresher", "it"], "role": "scene", "difficulty": "easy", "tags": ["problem-solving"], "language": "en"},
    {"id": "O20", "text": "I resist learning tools outside my immediate role.", "dimension": "openness", "reverse": True, "facet": "learning_resistance", "scenes": ["it", "ops", "enterprise"], "role": "scene", "difficulty": "easy", "tags": ["learning"], "language": "en"},

    # CONSCIENTIOUSNESS (21-40)
    {"id": "C21", "text": "I break large goals into weekly action steps.", "dimension": "conscientiousness", "reverse": False, "facet": "planning", "scenes": ["student", "fresher", "founder"], "role": "core", "difficulty": "easy", "tags": ["planning"], "language": "en"},
    {"id": "C22", "text": "I usually finish important tasks before deadlines.", "dimension": "conscientiousness", "reverse": False, "facet": "deadline", "scenes": ["it", "ops", "enterprise"], "role": "core", "difficulty": "easy", "tags": ["execution"], "language": "en"},
    {"id": "C23", "text": "I keep track of priorities even when work gets hectic.", "dimension": "conscientiousness", "reverse": False, "facet": "prioritization", "scenes": ["startup", "ops", "consulting"], "role": "core", "difficulty": "medium", "tags": ["focus"], "language": "en"},
    {"id": "C24", "text": "I prepare in advance for interviews, exams, or presentations.", "dimension": "conscientiousness", "reverse": False, "facet": "preparation", "scenes": ["student", "fresher", "career_switch"], "role": "core", "difficulty": "easy", "tags": ["career"], "language": "en"},
    {"id": "C25", "text": "I follow through on commitments even when motivation drops.", "dimension": "conscientiousness", "reverse": False, "facet": "discipline", "scenes": ["all"], "role": "core", "difficulty": "medium", "tags": ["consistency"], "language": "en"},
    {"id": "C26", "text": "I review my mistakes and adjust my process.", "dimension": "conscientiousness", "reverse": False, "facet": "self_correction", "scenes": ["all"], "role": "core", "difficulty": "medium", "tags": ["learning"], "language": "en"},
    {"id": "C27", "text": "I maintain organized notes or task systems.", "dimension": "conscientiousness", "reverse": False, "facet": "organization", "scenes": ["student", "it", "ops"], "role": "scene", "difficulty": "easy", "tags": ["systems"], "language": "en"},
    {"id": "C28", "text": "I prefer structured plans over last-minute decisions.", "dimension": "conscientiousness", "reverse": False, "facet": "structure", "scenes": ["enterprise", "gov", "student"], "role": "scene", "difficulty": "easy", "tags": ["planning"], "language": "en"},
    {"id": "C29", "text": "I set realistic milestones for career growth.", "dimension": "conscientiousness", "reverse": False, "facet": "goal_setting", "scenes": ["fresher", "career_switch", "founder"], "role": "scene", "difficulty": "medium", "tags": ["career"], "language": "en"},
    {"id": "C30", "text": "I can delay short-term pleasure for long-term goals.", "dimension": "conscientiousness", "reverse": False, "facet": "self_control", "scenes": ["all"], "role": "scene", "difficulty": "medium", "tags": ["discipline"], "language": "en"},
    {"id": "C31", "text": "I often postpone tasks until pressure becomes extreme.", "dimension": "conscientiousness", "reverse": True, "facet": "procrastination", "scenes": ["student", "fresher", "it"], "role": "reverse", "difficulty": "easy", "tags": ["habits"], "language": "en"},
    {"id": "C32", "text": "I start many things but leave important ones unfinished.", "dimension": "conscientiousness", "reverse": True, "facet": "follow_through", "scenes": ["startup", "student", "founder"], "role": "reverse", "difficulty": "easy", "tags": ["execution"], "language": "en"},
    {"id": "C33", "text": "I miss deadlines because I underestimate effort.", "dimension": "conscientiousness", "reverse": True, "facet": "estimation", "scenes": ["it", "ops", "consulting"], "role": "reverse", "difficulty": "medium", "tags": ["planning"], "language": "en"},
    {"id": "C34", "text": "I rely on mood rather than systems to stay productive.", "dimension": "conscientiousness", "reverse": True, "facet": "systems", "scenes": ["all"], "role": "reverse", "difficulty": "easy", "tags": ["consistency"], "language": "en"},
    {"id": "C35", "text": "I avoid planning because I think it limits freedom.", "dimension": "conscientiousness", "reverse": True, "facet": "planning_resistance", "scenes": ["startup", "creative", "student"], "role": "reverse", "difficulty": "easy", "tags": ["mindset"], "language": "en"},
    {"id": "C36", "text": "I get distracted easily during deep work.", "dimension": "conscientiousness", "reverse": True, "facet": "attention", "scenes": ["it", "student", "remote"], "role": "reverse", "difficulty": "easy", "tags": ["focus"], "language": "en"},
    {"id": "C37", "text": "I skip routine follow-ups after promising to do them.", "dimension": "conscientiousness", "reverse": True, "facet": "accountability", "scenes": ["enterprise", "sales", "ops"], "role": "scene", "difficulty": "easy", "tags": ["communication"], "language": "en"},
    {"id": "C38", "text": "I rarely track progress toward my career goals.", "dimension": "conscientiousness", "reverse": True, "facet": "tracking", "scenes": ["career_switch", "fresher", "student"], "role": "scene", "difficulty": "easy", "tags": ["career"], "language": "en"},
    {"id": "C39", "text": "I find consistency harder than I admit.", "dimension": "conscientiousness", "reverse": True, "facet": "consistency", "scenes": ["all"], "role": "scene", "difficulty": "easy", "tags": ["habits"], "language": "en"},
    {"id": "C40", "text": "I wait for perfect conditions before taking action.", "dimension": "conscientiousness", "reverse": True, "facet": "activation", "scenes": ["founder", "career_switch", "student"], "role": "scene", "difficulty": "easy", "tags": ["initiative"], "language": "en"},

    # EXTRAVERSION (41-60)
    {"id": "E41", "text": "I feel confident initiating conversations with new people.", "dimension": "extraversion", "reverse": False, "facet": "social_initiation", "scenes": ["networking", "fresher", "sales"], "role": "core", "difficulty": "easy", "tags": ["communication"], "language": "en"},
    {"id": "E42", "text": "I enjoy collaborative work with frequent interaction.", "dimension": "extraversion", "reverse": False, "facet": "sociability", "scenes": ["enterprise", "startup", "ops"], "role": "core", "difficulty": "easy", "tags": ["teamwork"], "language": "en"},
    {"id": "E43", "text": "I can present my ideas clearly in group settings.", "dimension": "extraversion", "reverse": False, "facet": "assertiveness", "scenes": ["it", "consulting", "student"], "role": "core", "difficulty": "medium", "tags": ["presentation"], "language": "en"},
    {"id": "E44", "text": "I like networking events when they are relevant to my goals.", "dimension": "extraversion", "reverse": False, "facet": "networking", "scenes": ["career_switch", "founder", "fresher"], "role": "core", "difficulty": "medium", "tags": ["career"], "language": "en"},
    {"id": "E45", "text": "I recover quickly after social or professional setbacks.", "dimension": "extraversion", "reverse": False, "facet": "social_resilience", "scenes": ["all"], "role": "core", "difficulty": "medium", "tags": ["resilience"], "language": "en"},
    {"id": "E46", "text": "I speak up when I have a useful viewpoint.", "dimension": "extraversion", "reverse": False, "facet": "voice", "scenes": ["meetings", "enterprise", "it"], "role": "core", "difficulty": "easy", "tags": ["confidence"], "language": "en"},
    {"id": "E47", "text": "I gain energy from active team environments.", "dimension": "extraversion", "reverse": False, "facet": "energy", "scenes": ["startup", "enterprise", "ops"], "role": "scene", "difficulty": "easy", "tags": ["work-style"], "language": "en"},
    {"id": "E48", "text": "I am comfortable contacting mentors or seniors for guidance.", "dimension": "extraversion", "reverse": False, "facet": "outreach", "scenes": ["student", "fresher", "career_switch"], "role": "scene", "difficulty": "easy", "tags": ["mentorship"], "language": "en"},
    {"id": "E49", "text": "I can keep conversations engaging in professional contexts.", "dimension": "extraversion", "reverse": False, "facet": "social_fluency", "scenes": ["sales", "hr", "consulting"], "role": "scene", "difficulty": "medium", "tags": ["communication"], "language": "en"},
    {"id": "E50", "text": "I often take initiative in team discussions.", "dimension": "extraversion", "reverse": False, "facet": "initiative", "scenes": ["team", "it", "ops"], "role": "scene", "difficulty": "easy", "tags": ["leadership"], "language": "en"},
    {"id": "E51", "text": "I avoid speaking unless someone directly asks me.", "dimension": "extraversion", "reverse": True, "facet": "reservedness", "scenes": ["meetings", "student", "enterprise"], "role": "reverse", "difficulty": "easy", "tags": ["communication"], "language": "en"},
    {"id": "E52", "text": "I feel drained by most social interactions at work.", "dimension": "extraversion", "reverse": True, "facet": "social_fatigue", "scenes": ["remote", "enterprise", "startup"], "role": "reverse", "difficulty": "easy", "tags": ["energy"], "language": "en"},
    {"id": "E53", "text": "I hesitate to share ideas even when I know they are useful.", "dimension": "extraversion", "reverse": True, "facet": "inhibition", "scenes": ["it", "consulting", "student"], "role": "reverse", "difficulty": "medium", "tags": ["confidence"], "language": "en"},
    {"id": "E54", "text": "I avoid networking because it feels pointless.", "dimension": "extraversion", "reverse": True, "facet": "network_avoidance", "scenes": ["career_switch", "fresher", "founder"], "role": "reverse", "difficulty": "easy", "tags": ["career"], "language": "en"},
    {"id": "E55", "text": "I prefer to stay invisible in meetings.", "dimension": "extraversion", "reverse": True, "facet": "visibility", "scenes": ["enterprise", "it", "ops"], "role": "reverse", "difficulty": "easy", "tags": ["work-style"], "language": "en"},
    {"id": "E56", "text": "I find it hard to approach unfamiliar colleagues.", "dimension": "extraversion", "reverse": True, "facet": "social_risk", "scenes": ["new_job", "enterprise", "student"], "role": "reverse", "difficulty": "easy", "tags": ["adaptation"], "language": "en"},
    {"id": "E57", "text": "I keep opportunities to myself instead of discussing them.", "dimension": "extraversion", "reverse": True, "facet": "sharing", "scenes": ["team", "founder", "fresher"], "role": "scene", "difficulty": "easy", "tags": ["teamwork"], "language": "en"},
    {"id": "E58", "text": "I rarely volunteer for visible responsibilities.", "dimension": "extraversion", "reverse": True, "facet": "ownership", "scenes": ["enterprise", "student", "it"], "role": "scene", "difficulty": "easy", "tags": ["leadership"], "language": "en"},
    {"id": "E59", "text": "I need strong external pressure to communicate proactively.", "dimension": "extraversion", "reverse": True, "facet": "proactivity", "scenes": ["ops", "sales", "remote"], "role": "scene", "difficulty": "medium", "tags": ["communication"], "language": "en"},
    {"id": "E60", "text": "I withdraw quickly when conversations become competitive.", "dimension": "extraversion", "reverse": True, "facet": "social_competition", "scenes": ["consulting", "sales", "startup"], "role": "scene", "difficulty": "medium", "tags": ["resilience"], "language": "en"},

    # AGREEABLENESS (61-80)
    {"id": "A61", "text": "I try to understand others before judging their behavior.", "dimension": "agreeableness", "reverse": False, "facet": "empathy", "scenes": ["team", "all"], "role": "core", "difficulty": "easy", "tags": ["empathy"], "language": "en"},
    {"id": "A62", "text": "I can disagree respectfully without damaging relationships.", "dimension": "agreeableness", "reverse": False, "facet": "respectful_conflict", "scenes": ["enterprise", "startup", "family_business"], "role": "core", "difficulty": "medium", "tags": ["conflict"], "language": "en"},
    {"id": "A63", "text": "I support teammates even when their style differs from mine.", "dimension": "agreeableness", "reverse": False, "facet": "cooperation", "scenes": ["team", "remote", "it"], "role": "core", "difficulty": "easy", "tags": ["teamwork"], "language": "en"},
    {"id": "A64", "text": "I value fairness in collaboration and credit-sharing.", "dimension": "agreeableness", "reverse": False, "facet": "fairness", "scenes": ["enterprise", "startup", "academia"], "role": "core", "difficulty": "easy", "tags": ["ethics"], "language": "en"},
    {"id": "A65", "text": "I stay polite under stress in professional settings.", "dimension": "agreeableness", "reverse": False, "facet": "civility", "scenes": ["customer-facing", "ops", "it"], "role": "core", "difficulty": "medium", "tags": ["professionalism"], "language": "en"},
    {"id": "A66", "text": "I am willing to help others when I have capacity.", "dimension": "agreeableness", "reverse": False, "facet": "helpfulness", "scenes": ["team", "all"], "role": "core", "difficulty": "easy", "tags": ["support"], "language": "en"},
    {"id": "A67", "text": "I listen carefully before responding in conflicts.", "dimension": "agreeableness", "reverse": False, "facet": "listening", "scenes": ["team", "family", "enterprise"], "role": "scene", "difficulty": "easy", "tags": ["communication"], "language": "en"},
    {"id": "A68", "text": "I prefer cooperation over unnecessary competition.", "dimension": "agreeableness", "reverse": False, "facet": "cooperative_orientation", "scenes": ["startup", "enterprise", "student"], "role": "scene", "difficulty": "easy", "tags": ["teamwork"], "language": "en"},
    {"id": "A69", "text": "I can admit when I am wrong.", "dimension": "agreeableness", "reverse": False, "facet": "humility", "scenes": ["all"], "role": "scene", "difficulty": "easy", "tags": ["self-awareness"], "language": "en"},
    {"id": "A70", "text": "I consider the impact of my words on others.", "dimension": "agreeableness", "reverse": False, "facet": "consideration", "scenes": ["team", "management", "family"], "role": "scene", "difficulty": "easy", "tags": ["communication"], "language": "en"},
    {"id": "A71", "text": "I become harsh when people work slower than me.", "dimension": "agreeableness", "reverse": True, "facet": "impatience", "scenes": ["team", "startup", "ops"], "role": "reverse", "difficulty": "easy", "tags": ["conflict"], "language": "en"},
    {"id": "A72", "text": "I often assume others are careless or selfish.", "dimension": "agreeableness", "reverse": True, "facet": "trust", "scenes": ["enterprise", "startup", "family_business"], "role": "reverse", "difficulty": "easy", "tags": ["mindset"], "language": "en"},
    {"id": "A73", "text": "I push my point even when compromise is better.", "dimension": "agreeableness", "reverse": True, "facet": "flexibility", "scenes": ["meetings", "team", "family"], "role": "reverse", "difficulty": "medium", "tags": ["collaboration"], "language": "en"},
    {"id": "A74", "text": "I treat disagreement as a personal attack.", "dimension": "agreeableness", "reverse": True, "facet": "defensiveness", "scenes": ["all"], "role": "reverse", "difficulty": "easy", "tags": ["emotions"], "language": "en"},
    {"id": "A75", "text": "I avoid helping unless there is direct benefit to me.", "dimension": "agreeableness", "reverse": True, "facet": "self_interest", "scenes": ["team", "networking", "enterprise"], "role": "reverse", "difficulty": "easy", "tags": ["teamwork"], "language": "en"},
    {"id": "A76", "text": "I struggle to appreciate contributions different from mine.", "dimension": "agreeableness", "reverse": True, "facet": "respect_for_diversity", "scenes": ["cross_functional", "it", "ops"], "role": "reverse", "difficulty": "medium", "tags": ["collaboration"], "language": "en"},
    {"id": "A77", "text": "I interrupt others when I feel strongly about a topic.", "dimension": "agreeableness", "reverse": True, "facet": "impulse_in_dialogue", "scenes": ["meetings", "debate", "team"], "role": "scene", "difficulty": "easy", "tags": ["communication"], "language": "en"},
    {"id": "A78", "text": "I hold grudges in team settings.", "dimension": "agreeableness", "reverse": True, "facet": "forgiveness", "scenes": ["team", "enterprise", "startup"], "role": "scene", "difficulty": "easy", "tags": ["relationships"], "language": "en"},
    {"id": "A79", "text": "I dismiss emotional concerns as weakness at work.", "dimension": "agreeableness", "reverse": True, "facet": "emotional_validation", "scenes": ["management", "team", "it"], "role": "scene", "difficulty": "medium", "tags": ["culture"], "language": "en"},
    {"id": "A80", "text": "I compete even when collaboration would improve outcomes.", "dimension": "agreeableness", "reverse": True, "facet": "competition_bias", "scenes": ["sales", "startup", "campus"], "role": "scene", "difficulty": "medium", "tags": ["teamwork"], "language": "en"},

    # NEUROTICISM (81-100)
    {"id": "N81", "text": "I worry that one career mistake will ruin my future.", "dimension": "neuroticism", "reverse": False, "facet": "catastrophizing", "scenes": ["fresher", "career_switch", "student"], "role": "core", "difficulty": "easy", "tags": ["anxiety"], "language": "en"},
    {"id": "N82", "text": "I overthink feedback for a long time.", "dimension": "neuroticism", "reverse": False, "facet": "rumination", "scenes": ["all"], "role": "core", "difficulty": "easy", "tags": ["feedback"], "language": "en"},
    {"id": "N83", "text": "I feel anxious before routine evaluations or reviews.", "dimension": "neuroticism", "reverse": False, "facet": "evaluation_stress", "scenes": ["enterprise", "student", "it"], "role": "core", "difficulty": "easy", "tags": ["stress"], "language": "en"},
    {"id": "N84", "text": "I struggle to relax when work uncertainty increases.", "dimension": "neuroticism", "reverse": False, "facet": "uncertainty_stress", "scenes": ["startup", "career_switch", "ops"], "role": "core", "difficulty": "medium", "tags": ["uncertainty"], "language": "en"},
    {"id": "N85", "text": "I often compare my progress with peers and feel behind.", "dimension": "neuroticism", "reverse": False, "facet": "social_comparison", "scenes": ["student", "fresher", "social_media"], "role": "core", "difficulty": "easy", "tags": ["comparison"], "language": "en"},
    {"id": "N86", "text": "I feel stressed when plans change suddenly.", "dimension": "neuroticism", "reverse": False, "facet": "change_stress", "scenes": ["all"], "role": "core", "difficulty": "easy", "tags": ["adaptability"], "language": "en"},
    {"id": "N87", "text": "I find it hard to disconnect from work-related concerns.", "dimension": "neuroticism", "reverse": False, "facet": "detachment", "scenes": ["it", "founder", "ops"], "role": "scene", "difficulty": "medium", "tags": ["burnout"], "language": "en"},
    {"id": "N88", "text": "I react strongly to criticism, even when it is constructive.", "dimension": "neuroticism", "reverse": False, "facet": "reactivity", "scenes": ["all"], "role": "scene", "difficulty": "easy", "tags": ["feedback"], "language": "en"},
    {"id": "N89", "text": "I fear disappointing family expectations about career choices.", "dimension": "neuroticism", "reverse": False, "facet": "family_pressure", "scenes": ["student", "fresher", "career_switch"], "role": "scene", "difficulty": "easy", "tags": ["india-context"], "language": "en"},
    {"id": "N90", "text": "I lose confidence quickly after setbacks.", "dimension": "neuroticism", "reverse": False, "facet": "confidence_recovery", "scenes": ["all"], "role": "scene", "difficulty": "easy", "tags": ["resilience"], "language": "en"},
    {"id": "N91", "text": "I stay calm when outcomes are uncertain.", "dimension": "neuroticism", "reverse": True, "facet": "calmness", "scenes": ["startup", "enterprise", "student"], "role": "reverse", "difficulty": "easy", "tags": ["stability"], "language": "en"},
    {"id": "N92", "text": "I recover emotionally soon after a difficult day.", "dimension": "neuroticism", "reverse": True, "facet": "recovery", "scenes": ["all"], "role": "reverse", "difficulty": "easy", "tags": ["resilience"], "language": "en"},
    {"id": "N93", "text": "I can separate temporary failure from self-worth.", "dimension": "neuroticism", "reverse": True, "facet": "self_worth", "scenes": ["all"], "role": "reverse", "difficulty": "medium", "tags": ["mindset"], "language": "en"},
    {"id": "N94", "text": "I handle pressure without panic in most situations.", "dimension": "neuroticism", "reverse": True, "facet": "pressure_tolerance", "scenes": ["it", "ops", "healthcare"], "role": "reverse", "difficulty": "medium", "tags": ["stress"], "language": "en"},
    {"id": "N95", "text": "I maintain perspective during career transitions.", "dimension": "neuroticism", "reverse": True, "facet": "transition_stability", "scenes": ["career_switch", "fresher", "founder"], "role": "reverse", "difficulty": "medium", "tags": ["career"], "language": "en"},
    {"id": "N96", "text": "I can tolerate ambiguity while making decisions.", "dimension": "neuroticism", "reverse": True, "facet": "ambiguity_tolerance", "scenes": ["startup", "management", "consulting"], "role": "reverse", "difficulty": "medium", "tags": ["decision-making"], "language": "en"},
    {"id": "N97", "text": "I remain steady even when others are stressed.", "dimension": "neuroticism", "reverse": True, "facet": "emotional_containment", "scenes": ["team", "management", "family"], "role": "scene", "difficulty": "medium", "tags": ["leadership"], "language": "en"},
    {"id": "N98", "text": "I can pause and respond thoughtfully under pressure.", "dimension": "neuroticism", "reverse": True, "facet": "response_control", "scenes": ["all"], "role": "scene", "difficulty": "easy", "tags": ["self-control"], "language": "en"},
    {"id": "N99", "text": "I bounce back after rejection or negative feedback.", "dimension": "neuroticism", "reverse": True, "facet": "bounce_back", "scenes": ["job_search", "sales", "founder"], "role": "scene", "difficulty": "easy", "tags": ["resilience"], "language": "en"},
    {"id": "N100", "text": "I sleep reasonably well even during busy periods.", "dimension": "neuroticism", "reverse": True, "facet": "sleep_regulation", "scenes": ["all"], "role": "scene", "difficulty": "easy", "tags": ["wellbeing"], "language": "en"},
]


def get_question_pool(version: str | None = None) -> list[dict]:
    _ = version or settings.QUESTION_BANK_VERSION
    return QUESTIONS


def get_question_map() -> dict[str, dict]:
    return {q["id"]: q for q in QUESTIONS}


def get_question_by_ids(ids: list[str]) -> list[dict]:
    qmap = get_question_map()
    return [qmap[qid] for qid in ids if qid in qmap]


def get_all_questions() -> list[dict]:
    """Backward-compatible endpoint payload: return a deterministic 40-item default set."""
    selected: list[dict] = []
    for dim in DIMENSIONS:
        dim_items = [q for q in QUESTIONS if q["dimension"] == dim]
        selected.extend(dim_items[:8])
    return selected
